# Generated by Django 3.1.4 on 2021-03-14 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Вид груза')),
                ('cargo_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Вид груза',
                'verbose_name_plural': 'Виды грузов',
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_1', models.CharField(max_length=150, verbose_name='Город 1')),
                ('city_2', models.CharField(max_length=150, verbose_name='Город 2')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('price_1_5t', models.IntegerField(verbose_name='Стоимость до 1.5 тонн')),
                ('price_3t', models.IntegerField(verbose_name='Стоимость до 3 тонн')),
                ('price_5t', models.IntegerField(verbose_name='Стоимость до 5 тонн')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_road', models.CharField(max_length=1500, verbose_name='Маршрут')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ')),
                ('road_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге')),
                ('cargo_type', models.CharField(blank=True, max_length=60, verbose_name='Тип груза')),
                ('cargo_type_comment', models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('prices', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа')),
                ('user_tel_nomer', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('sended_in', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 21, 22, 27, 862867), null=True, verbose_name='Время отправки заявки')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа')),
                ('author', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.IntegerField(blank=True, default=1, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
