# Generated by Django 3.1.4 on 2021-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_adress', models.CharField(max_length=150, verbose_name='Откуда')),
                ('to_adress', models.CharField(max_length=150, verbose_name='Куда')),
                ('road_comment', models.TextField(verbose_name='Комментарий к доргоге')),
                ('gruz_type', models.CharField(max_length=50, verbose_name='Тип груза')),
                ('gruz_type_comment', models.TextField(verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(max_length=2, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(max_length=2, verbose_name='Количество часов для грузчиков')),
                ('user_tel_nomer', models.IntegerField(max_length=12, verbose_name='Номер телефона заказчика')),
            ],
        ),
    ]
