# Generated by Django 3.1.4 on 2021-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_road', models.CharField(verbose_name='Маршрут', max_length=1500)),
                ('road_comment', models.TextField(verbose_name='Комментарий к доргоге')),
                ('cargo_type', models.CharField(verbose_name='Тип груза', max_length=60, blank=True)),
                ('cargo_type_comment', models.TextField(verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(max_length=2, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(max_length=2, verbose_name='Количество часов для грузчиков')),
                ('user_tel_nomer', models.IntegerField(max_length=12, verbose_name='Номер телефона заказчика')),
            ],
        ),
    ]
