# Generated by Django 3.1.4 on 2021-03-12 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Вид груза')),
                ('cargo_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Вид груза',
                'verbose_name_plural': 'Виды грузов',
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_1', models.CharField(max_length=150, verbose_name='Город 1')),
                ('city_2', models.CharField(max_length=150, verbose_name='Город 2')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('price_1_5t', models.IntegerField(verbose_name='Стоимость до 1.5 тонн')),
                ('price_3t', models.IntegerField(verbose_name='Стоимость до 3 тонн')),
                ('price_5t', models.IntegerField(verbose_name='Стоимость до 5 тонн')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prices',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 15, 26, 35, 347356), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_type_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loader_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loader_time_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков'),
        ),
        migrations.AlterField(
            model_name='order',
            name='road_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_tel_nomer',
            field=models.CharField(max_length=20, verbose_name='Номер телефона заказчика'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.IntegerField(blank=True, default=1, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
