# Generated by Django 3.1.4 on 2021-06-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.driverprofile'),
            preserve_default=False,
        ),
    ]
