# Generated by Django 3.1.4 on 2021-03-17 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tel_number', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('sended_in', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 17, 22, 3, 18, 589627), null=True, verbose_name='Время отправки заявки')),
                ('author', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 17, 22, 3, 18, 589627), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
