# Generated by Django 3.1.4 on 2021-06-13 14:25

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 17, 25, 42, 753156), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='canceled_orders',
            field=models.IntegerField(blank=True, verbose_name='Отмененные заказы'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='complited_orders',
            field=models.IntegerField(blank=True, verbose_name='Завершенные заказы'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='dispatcher_rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг Диспетчера'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='passport_number',
            field=models.IntegerField(verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='passport_series',
            field=models.IntegerField(verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='registration_address',
            field=models.CharField(max_length=250, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='canceled_orders',
            field=models.IntegerField(blank=True, verbose_name='Отмененные заказы'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='complited_orders',
            field=models.IntegerField(blank=True, verbose_name='Завершенные заказы'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_licenses_number',
            field=models.IntegerField(verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_licenses_series',
            field=models.IntegerField(verbose_name='Серия водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг водителя'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='passport_number',
            field=models.IntegerField(verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='passport_series',
            field=models.IntegerField(verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='driver_licenses_number',
            field=models.IntegerField(blank=True, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='driver_licenses_series',
            field=models.IntegerField(blank=True, verbose_name='Серия водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='passport_number',
            field=models.IntegerField(verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='passport_series',
            field=models.IntegerField(verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 17, 25, 42, 751154), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 17, 25, 42, 759158), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
