# Generated by Django 3.1.4 on 2021-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия на заказ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gruz_type_comment',
            field=models.TextField(null=True, verbose_name='Тип груза комментарий'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='loader_count',
            field=models.IntegerField(max_length=2, null=True, verbose_name='Количество грузчиков'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='loader_time_count',
            field=models.IntegerField(max_length=2, null=True, verbose_name='Количество часов для грузчиков'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='road_comment',
            field=models.TextField(null=True, verbose_name='Комментарий к доргоге'),
        ),
    ]
