# Generated by Django 3.1.4 on 2021-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210614_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_orders',
            field=models.IntegerField(blank=True, default=0, verbose_name='Текущие заказы'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='canceled_orders',
            field=models.IntegerField(blank=True, default=0, verbose_name='Отмененные заказы'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='complited_orders',
            field=models.IntegerField(blank=True, default=0, verbose_name='Завершенные заказы'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг водителя'),
        ),
    ]
