# Generated by Django 3.1.4 on 2021-01-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210107_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_tel_nomer',
            field=models.CharField(max_length=20, verbose_name='Номер телефона заказчика'),
        ),
    ]
