# Generated by Django 3.1.4 on 2021-04-04 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210317_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='telorder',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 6, 52, 59, 492898), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 6, 52, 59, 498747), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='user_tel_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
