# Generated by Django 3.1.4 on 2021-06-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210614_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driverprofile'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=9, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='car',
            name='width',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ширина'),
        ),
    ]
