# Generated by Django 3.1.4 on 2021-04-11 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210404_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 11, 11, 23, 11, 593842), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 11, 11, 23, 11, 599701), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
