# Generated by Django 3.1.4 on 2021-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210108_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gruz_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gruz_type_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='loader_count',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Количество грузчиков'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='loader_time_count',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Количество часов для грузчиков'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='road_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ'),
        ),
    ]
