# Generated by Django 3.1.4 on 2021-04-11 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210411_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 11, 18, 4, 41, 318533), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 11, 18, 4, 41, 323416), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
