# Generated by Django 3.1.4 on 2021-01-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Adresses',
        ),
    ]
