# Generated by Django 3.1.4 on 2021-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_driverprofile_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='registration_address',
            field=models.CharField(max_length=250, verbose_name='Адрес прописки'),
        ),
    ]
