# Generated by Django 3.1.4 on 2021-05-11 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210411_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplitedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_road', models.CharField(max_length=1500, verbose_name='Маршрут')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ')),
                ('road_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге')),
                ('cargo_type', models.CharField(blank=True, max_length=60, verbose_name='Тип груза')),
                ('cargo_type_comment', models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('prices', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа')),
                ('user_tel_nomer', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('sended_in', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 11, 20, 20, 45, 807912), null=True, verbose_name='Время отправки заявки')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа')),
                ('author', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора')),
            ],
            options={
                'verbose_name': 'Завершенный заказ',
                'verbose_name_plural': 'Завершенные заказы',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(default=89, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 11, 20, 20, 45, 806912), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 11, 20, 20, 45, 810992), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
