# Generated by Django 3.2.4 on 2021-06-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_companyregularorder'),
        ('core', '0006_auto_20210615_1355'),
    ]

    operations = [
    ]
