# Generated by Django 3.1.4 on 2021-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210111_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresses',
            name='adress',
        ),
        migrations.AddField(
            model_name='adresses',
            name='adress1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес1'),
        ),
        migrations.AddField(
            model_name='adresses',
            name='adress2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес2'),
        ),
    ]
