# Generated by Django 3.1.4 on 2021-05-18 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20210517_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='registration_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 39, 27, 645278), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_licenses_number',
            field=models.CharField(max_length=6, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_licenses_series',
            field=models.CharField(max_length=4, verbose_name='Серия водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='passport_number',
            field=models.CharField(max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='passport_series',
            field=models.CharField(max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 39, 27, 629653), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 39, 27, 645278), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('registration_address', models.CharField(blank=True, max_length=250, verbose_name='Номер водительского удостоверения')),
                ('driver_licenses_series', models.CharField(blank=True, max_length=4, verbose_name='Серия водительского удостоверения')),
                ('driver_licenses_number', models.CharField(blank=True, max_length=6, verbose_name='Номер водительского удостоверения')),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
