# Generated by Django 3.1.4 on 2021-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210111_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresses',
            name='adress1',
        ),
        migrations.RemoveField(
            model_name='adresses',
            name='adress2',
        ),
        migrations.AddField(
            model_name='adresses',
            name='adress',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес'),
        ),
    ]
