# Generated by Django 3.1.4 on 2021-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210111_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_1', models.CharField(max_length=150, verbose_name='Город 1')),
                ('city_2', models.CharField(max_length=150, verbose_name='Город 2')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterModelOptions(
            name='adresses',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
