# Generated by Django 3.1.4 on 2021-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210615_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identificator',
            field=models.CharField(max_length=20, null=True, verbose_name='Идентификатор заказа'),
        ),
    ]
