# Generated by Django 3.1.4 on 2021-05-18 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210518_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 52, 52, 749347), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='registration_address',
            field=models.CharField(max_length=250, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='registration_address',
            field=models.CharField(max_length=250, verbose_name='Адресс прописки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 52, 52, 747346), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 14, 52, 52, 759351), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
