# Generated by Django 3.1.4 on 2021-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210112_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='loader_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='loader_time_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков'),
        ),
    ]
