# Generated by Django 3.1.4 on 2021-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_identificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Статус компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='identificator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор заказа'),
        ),
    ]
