# Generated by Django 3.1.4 on 2021-01-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210112_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citys_price',
            new_name='City_Price',
        ),
    ]
