# Generated by Django 3.1.4 on 2021-05-21 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210518_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatcher',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID диспетчера'),
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 8, 11, 46, 249595), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 8, 11, 46, 249595), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 8, 11, 46, 249595), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('registration_number', models.CharField(max_length=9, verbose_name='Регистрационные номера')),
                ('length', models.CharField(max_length=4, verbose_name='Длина')),
                ('height', models.CharField(max_length=4, verbose_name='Высота')),
                ('width', models.CharField(max_length=4, verbose_name='Ширина')),
                ('volume', models.CharField(max_length=4, verbose_name='Объём')),
                ('tonnage', models.CharField(max_length=4, verbose_name='Тоннаж')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
