# Generated by Django 3.1.4 on 2021-01-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210112_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City_Price',
            new_name='CityPrice',
        ),
    ]
