# Generated by Django 3.1.4 on 2021-05-21 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210521_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Вид деятельности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 12, 16, 4, 424021), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_rating',
            field=models.CharField(blank=True, default=0, max_length=40, verbose_name='Рейтинг водителя'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='registration_address',
            field=models.CharField(max_length=250, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 12, 16, 4, 413506), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 12, 16, 4, 424021), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
