# Generated by Django 3.1.4 on 2021-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210112_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprice',
            name='gruz_weight',
            field=models.IntegerField(default=(1, 5), verbose_name='Вес груза'),
            preserve_default=False,
        ),
    ]
