# Generated by Django 3.1.4 on 2021-05-24 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210521_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 11, 56, 43, 155111), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 11, 56, 43, 153108), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 11, 56, 43, 160111), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
