# Generated by Django 3.1.4 on 2021-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cityprice_gruz_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprice',
            old_name='price',
            new_name='price_1_5t',
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='gruz_weight',
        ),
        migrations.AddField(
            model_name='cityprice',
            name='price_5t',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
