# Generated by Django 3.1.4 on 2021-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210112_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprice',
            name='price_1_5t',
            field=models.IntegerField(verbose_name='Стоимость до 1.5 тонн'),
        ),
        migrations.AlterField(
            model_name='cityprice',
            name='price_5t',
            field=models.IntegerField(verbose_name='Стоимость до 5 тонн'),
        ),
    ]
