# Generated by Django 3.1.4 on 2021-05-24 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210524_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 12, 55, 53, 44), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 12, 55, 52, 998045), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 12, 55, 53, 10048), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
