# Generated by Django 3.1.4 on 2021-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210112_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprice',
            name='price_3t',
            field=models.IntegerField(default=0, verbose_name='Стоимость до 3 тонн'),
            preserve_default=False,
        ),
    ]
