# Generated by Django 3.1.4 on 2021-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cityprice_price_3t'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(default=500, verbose_name='Стоимость заказа'),
            preserve_default=False,
        ),
    ]
