# Generated by Django 3.1.4 on 2021-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orders_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='gruz_type',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='gruz_type_comment',
        ),
        migrations.AddField(
            model_name='orders',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cargo_type_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий'),
        ),
    ]
