# Generated by Django 3.1.4 on 2021-05-27 03:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20210527_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 6, 19, 51, 124466), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='core.driverprofile', verbose_name='driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 6, 19, 51, 122466), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 6, 19, 51, 129466), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('registration_address', models.CharField(max_length=250, verbose_name='Адрес прописки')),
                ('complited_orders', models.CharField(blank=True, max_length=40, verbose_name='Завершенные заказы')),
                ('canceled_orders', models.CharField(blank=True, max_length=40, verbose_name='Отмененные заказы')),
                ('dispatcher_rating', models.CharField(blank=True, default=0, max_length=40, verbose_name='Рейтинг Диспетчера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatcher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to='core.dispatcherprofile', verbose_name='dispatcher'),
            preserve_default=False,
        ),
    ]
