# Generated by Django 3.1.4 on 2021-01-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cargotype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargotype',
            options={'verbose_name': 'Вид груза', 'verbose_name_plural': 'Виды грузов'},
        ),
    ]
