# Generated by Django 3.1.4 on 2021-05-27 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210527_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=150, verbose_name='Ответ пользователя')),
                ('text', models.IntegerField(blank=True, max_length=150, verbose_name='Текст')),
                ('function_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'Ответ ассистента',
                'verbose_name_plural': 'Словарь ассистента',
            },
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 32, 56, 574242), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 32, 56, 573242), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 32, 56, 578243), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
