# Generated by Django 3.1.4 on 2021-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210120_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Состояние заказа'),
        ),
    ]
