# Generated by Django 3.1.4 on 2021-05-27 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210527_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantlibrary',
            name='text',
        ),
        migrations.AddField(
            model_name='assistantlibrary',
            name='assistant_text',
            field=models.TextField(blank=True, verbose_name='Текст ассистента'),
        ),
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 57, 22, 893407), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 57, 22, 892409), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 15, 57, 22, 898410), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
