# Generated by Django 3.1.4 on 2021-06-09 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210527_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 20, 37, 33, 985582), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='canceled_orders',
            field=models.IntegerField(blank=True, max_length=40, verbose_name='Отмененные заказы'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='complited_orders',
            field=models.IntegerField(blank=True, max_length=40, verbose_name='Завершенные заказы'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='dispatcher_rating',
            field=models.IntegerField(blank=True, default=0, max_length=40, verbose_name='Рейтинг Диспетчера'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='passport_number',
            field=models.IntegerField(max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='passport_series',
            field=models.IntegerField(max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='dispatcherprofile',
            name='registration_address',
            field=models.IntegerField(max_length=250, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 20, 37, 33, 985582), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 20, 37, 33, 985582), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
