# Generated by Django 3.1.4 on 2021-01-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='from_adress',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to_adress',
            new_name='to_address',
        ),
    ]
