# Generated by Django 3.2 on 2021-06-13 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210609_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complitedorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 15, 45, 13, 891287), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 15, 45, 13, 890243), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='telorder',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 15, 45, 13, 893243), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
