# Generated by Django 3.1.4 on 2021-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_full_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа'),
        ),
    ]
