# Generated by Django 3.1.4 on 2021-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_date',
            new_name='published_date',
        ),
    ]
