# Generated by Django 3.1.4 on 2021-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210217_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prices',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа'),
        ),
    ]
