# Generated by Django 3.2 on 2021-06-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.car'),
        ),
    ]
