# Generated by Django 3.1.4 on 2021-02-18 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_address',
        ),
        migrations.AddField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 6, 53, 16, 554744), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
