# Generated by Django 3.1.4 on 2021-02-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210216_1814'),
        ('core', '0029_auto_20210218_0653'),
    ]

    operations = [
    ]
