# Generated by Django 3.1.4 on 2021-03-02 17:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210302_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 20, 7, 2, 292370), null=True, verbose_name='Время отправки заявки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(),
        ),
    ]
