# Generated by Django 3.1.4 on 2021-03-02 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210302_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 20, 11, 40, 70303), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
