# Generated by Django 3.1.4 on 2021-03-03 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210302_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_road',
            field=models.CharField(max_length=1500, verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 17, 21, 9, 456392), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
