# Generated by Django 3.1.4 on 2021-03-10 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210303_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 11, 7, 37, 838370), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
