# Generated by Django 3.1.4 on 2021-03-12 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210310_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sended_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 6, 20, 16, 300159), null=True, verbose_name='Время отправки заявки'),
        ),
    ]
