# Generated by Django 3.1.4 on 2021-06-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=150, verbose_name='Ответ пользователя')),
                ('assistant_text', models.TextField(blank=True, verbose_name='Текст ассистента')),
                ('function_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'Ответ ассистента',
                'verbose_name_plural': 'Словарь ассистента',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='Имя компании')),
                ('company_inn', models.CharField(max_length=12, verbose_name='ИНН компании')),
                ('business_type', models.CharField(max_length=128, verbose_name='Вид деятельности')),
                ('legal_address', models.CharField(max_length=128, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(max_length=128, verbose_name='Фактический адрес')),
                ('contact_name', models.CharField(max_length=128, verbose_name='Имя контакта')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='Телефон контакта')),
                ('contact_email', models.EmailField(max_length=64, verbose_name='Эл.почта контакта')),
                ('status', models.BooleanField(default=0, verbose_name='Статус компании')),
                ('contact_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.IntegerField(blank=True, default=1, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50, verbose_name='Вид деятельности')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('registration_address', models.CharField(max_length=250, verbose_name='Адресс прописки')),
                ('driver_licenses_series', models.CharField(blank=True, max_length=4, verbose_name='Серия водительского удостоверения')),
                ('driver_licenses_number', models.CharField(blank=True, max_length=6, verbose_name='Номер водительского удостоверения')),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('schedule', models.CharField(max_length=64, verbose_name='Расписание грузоперевозок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_regular_order', to='core.company')),
            ],
            bases=('order.order',),
        ),
    ]
