# Generated by Django 3.2.4 on 2021-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyOrder',
        ),
    ]
