# Generated by Django 3.1.4 on 2021-06-26 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Вид груза')),
                ('cargo_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Вид груза',
                'verbose_name_plural': 'Виды грузов',
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_1', models.CharField(max_length=150, verbose_name='Город 1')),
                ('city_2', models.CharField(max_length=150, verbose_name='Город 2')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('price_1_5t', models.IntegerField(verbose_name='Стоимость до 1.5 тонн')),
                ('price_3t', models.IntegerField(verbose_name='Стоимость до 3 тонн')),
                ('price_5t', models.IntegerField(verbose_name='Стоимость до 5 тонн')),
            ],
        ),
        migrations.CreateModel(
            name='ComplitedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_road', models.CharField(max_length=1500, verbose_name='Маршрут')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ')),
                ('road_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге')),
                ('cargo_type', models.CharField(blank=True, max_length=60, verbose_name='Тип груза')),
                ('cargo_type_comment', models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('prices', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа')),
                ('user_tel_nomer', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('sended_in', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки заявки')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа')),
                ('author', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора')),
            ],
            options={
                'verbose_name': 'Завершенный заказ',
                'verbose_name_plural': 'Завершенные заказы',
            },
        ),
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
                ('registration_address', models.CharField(max_length=250, verbose_name='Адрес прописки')),
                ('complited_orders', models.IntegerField(blank=True, verbose_name='Завершенные заказы')),
                ('canceled_orders', models.IntegerField(blank=True, verbose_name='Отмененные заказы')),
                ('dispatcher_rating', models.IntegerField(blank=True, default=0, verbose_name='Рейтинг Диспетчера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('driver_licenses_series', models.CharField(max_length=4, verbose_name='Серия водительского удостоверения')),
                ('driver_licenses_number', models.CharField(max_length=6, verbose_name='Номер водительского удостоверения')),
                ('registration_address', models.CharField(max_length=250, verbose_name='Адрес прописки')),
                ('current_orders', models.IntegerField(blank=True, default=0, verbose_name='Текущие заказы')),
                ('complited_orders', models.IntegerField(blank=True, default=0, verbose_name='Завершенные заказы')),
                ('canceled_orders', models.IntegerField(blank=True, default=0, verbose_name='Отмененные заказы')),
                ('driver_rating', models.IntegerField(blank=True, default=0, verbose_name='Рейтинг водителя')),
                ('telephone_number', models.CharField(blank=True, default=0, max_length=20, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя заказчика')),
                ('user_tel_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('sended_in', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки заявки')),
                ('author', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Автора')),
            ],
        ),
        migrations.CreateModel(
            name='XeroConnectionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_road', models.CharField(max_length=1500, verbose_name='Маршрут')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия на заказ')),
                ('road_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к доргоге')),
                ('cargo_type', models.CharField(blank=True, max_length=60, verbose_name='Тип груза')),
                ('cargo_type_comment', models.TextField(blank=True, null=True, verbose_name='Тип груза комментарий')),
                ('loader_count', models.IntegerField(blank=True, null=True, verbose_name='Количество грузчиков')),
                ('loader_time_count', models.IntegerField(blank=True, null=True, verbose_name='Количество часов для грузчиков')),
                ('order_price', models.IntegerField(verbose_name='Стоимость заказа')),
                ('prices', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цены заказа')),
                ('user_tel_nomer', models.CharField(max_length=20, verbose_name='Номер телефона заказчика')),
                ('sended_in', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки заявки')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Состояние заказа')),
                ('identificator', models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор заказа')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to='order.dispatcherprofile', verbose_name='dispatcher')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='order.driverprofile', verbose_name='driver')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('registration_number', models.CharField(max_length=9, verbose_name='Регистрационный номер')),
                ('length', models.CharField(max_length=4, verbose_name='Длина')),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='Высота')),
                ('width', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ширина')),
                ('volume', models.CharField(blank=True, max_length=4, null=True, verbose_name='Объём')),
                ('tonnage', models.CharField(max_length=4, verbose_name='Тоннаж')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.driverprofile')),
            ],
        ),
    ]
