# Generated by Django 3.2.4 on 2021-06-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_companyorder'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('schedule', models.CharField(max_length=64, verbose_name='Расписание грузоперевозок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_regular_order', to='core.company')),
            ],
            bases=('order.order',),
        ),
    ]
